### ISSUE TITLE
MalformedURLException: URI passed is malformed

### ISSUE THREAD

**Issue by CFPrulez** [DSteve595/EmojiSwitcher#19]
The files cannot be downloaded.

Stacktrace:

```
System.out  I  ######## DownloadRequestQueue mDelivery in ####### com.thin.downloadmanager.DownloadRequestQueue$a@f20386c
ThinDownloadManager  V  Download initiated for 1
ThinDownloadManager  V  Response code obtained for downloaded Id 1 : httpResponse Code 301
ThinDownloadManager  V  Redirect for downloaded Id 1
ThinDownloadManager  D  cleanupDestination() deleting /data/user/0/com.stevenschoen.emojiswitcher/files/emojisets/iOS102.ttf
System.err  W  java.lang.Exception: Download failed, code MalformedURLException: URI passed is malformed.: MalformedURLException: URI passed is malformed.
System.err  W  at com.stevenschoen.emojiswitcher.EmojiSwitcherUtils$1$4.onDownloadFailed(EmojiSwitcherUtils.java:195)
System.err  W  at com.thin.downloadmanager.DownloadRequestQueue$a$3.run(DownloadRequestQueue.java:69)
System.err  W  at android.os.Handler.handleCallback(Handler.java:751)
System.err  W  at android.os.Handler.dispatchMessage(Handler.java:95)
System.err  W  at android.os.Looper.loop(Looper.java:154)
System.err  W  at android.app.ActivityThread.main(ActivityThread.java:6236)
System.err  W  at java.lang.reflect.Method.invoke(Native Method)
System.err  W  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
System.err  W  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by BlueDrink9** [comment]
I'm getting this too on Android 6.0. Happens for all icon packs.
