### ISSUE TITLE
Crash at start (new)

### ISSUE THREAD

**Issue by NerosTie** [DSteve595/EmojiSwitcher#9]
With the version 2.1, I have still a crash at start.

Report:

```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
   at android.app.ActivityThread.installProvider(ActivityThread.java:4982)
   at android.app.ActivityThread.installContentProviders(ActivityThread.java:4574)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4514)
   at android.app.ActivityThread.access$1500(ActivityThread.java:147)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1346)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5238)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)
Caused by: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
   at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
   at android.app.ActivityThread.installProvider(ActivityThread.java:4979)
   ... 11 more
```

**Comment by DSteve595** [comment]
Sorry about that! Fixed.

**Comment by NerosTie** [comment]
It was quick! It works, thanks!
